FROM maven:3.6.3-jdk-8 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn dependency:go-offline -B
RUN mvn test
RUN mvn package
FROM openjdk:8-jre-slim
WORKDIR /app
COPY --from=build /app/target/*.war app.war
ENTRYPOINT ["java","-jar","app.war"]